### ISSUE TITLE
The user can't interact with search suggestions in tooltips

### ISSUE THREAD

**Issue by Ostrzyciel** [rdzanyM/science_points#58]
The tooltips suggest other possible matches, but there is no way to interact with this suggestion.
![image](https://user-images.githubusercontent.com/56843159/118444507-7f0d1400-b6ed-11eb-8644-5f48e229582c.png)

Possible new feature: allow the user to substitute the match in the table simply by clicking on the suggestion. This could require moving the suggestion outside the tooltip, or at least replicating it. The sidebar maybe?

**Comment by YuseqYaseq** [comment]
Unfortunately due to dash limitations implementing this feature as a tooltip or sidebar link would require either creating god function, moving to another framework completely or would cause stuttering in the application view. After a lengthy meeting it was unanimously decided that implementation costs would be too high and instead a simple sidebar text message was implemented.
